### ISSUE TITLE
<%= form_tag post_path(@post), method: "put" do %> doesn't work

### ISSUE THREAD

**Issue by lennhy** [learn-co-curriculum/rails-edit-update-action-readme#10]
Including this in the edit form "<%= form_tag post_path(@post), method: "put" do %>
" gives an error and breaks the code.

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback.

I was unable to reproduce this issue, but we have updated the materials in this lesson to now use form_for and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
