### ISSUE TITLE
form_for uses PATCH automatically. NOT PUT.

### ISSUE THREAD

**Issue by yehudamakarov** [learn-co-curriculum/rails-edit-update-action-readme#13]
We also can remove the path argument and the method call since form_for will automatically set these for us. How does form_for know that we want to use PUT for the form method? It's smart enough to know that since it's dealing with a pre-existing record you want to utilize PUT over POST.

Should be PATHC not PUT.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @yehudamakarov.

We have updated the materials to use form_for and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
