### ISSUE TITLE
spec/features/post_spec.rb needs to be updated

### ISSUE THREAD

**Issue by OneCuteLiz** [learn-co-curriculum/rails-edit-update-action-readme#14]
**GIVEN THE FOLLOWING SPEC and ERB files:**

``` 
#spec/features/post_spec.rb

it 'shows a new form that submits content and redirects and prints out params' do
    @post = Post.create(title: "My Post", description: "My post desc")

    visit edit_post_path(@post)

    fill_in 'title', with: "My edit"
    fill_in 'description', with: "My post description"

    click_on "Submit Post"

    expect(page).to have_content("My edit")


#app/views/posts/edit.html.rb

<%= form_for @post do |f| %>
  <%= f.label 'Post Title' %><br>
  <%= f.text_field :title %><br>
 
  <%= f.label 'Post Description' %><br>
  <%= f.text_area :description %><br>
 
  <%= f.submit "Submit Post" %>
<% end %>
```

**EXPECTED UPDATE:**
```
#spec/features/post_soec.rb

...
fill_in 'post_title', with "My edit"
...
fill_in 'post_description', with: "My post description"
...
```

**WHAT'S HAPPENING**
I'm failing my test for this lab because it's looking for a field with an `id="title"`.  Using `<%= form_for @post do |f| %>` you always get an `id="post_title"`. Unless I'm missing something I believe the test spec should be updated as such.

**Comment by anikonchuk** [comment]
I had the same issue... Also, in the instructions for the controller, because the form_for tag updates the "name" field as well, the correct "update" line should be 
@post.update(title: params[:post][:title], description: params[:post][:description])

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
