### ISSUE TITLE
This lesson only passes if you don't update the form as the readme suggests.

### ISSUE THREAD

**Issue by emilywelsch** [learn-co-curriculum/rails-edit-update-action-readme#15]
The lesson tells you to change the edit view from:

<%= form_tag post_path(@post), method: "put" do %>
  <label>Post title:</label><br>
  <%= text_field_tag :title, @post.title %><br>

  <label>Post Description</label><br>
  <%= text_area_tag :description, @post.description %><br>

  <%= submit_tag "Submit Post" %>
<% end %>

To the following:

<%= form_for @post do |f| %>
  <%= f.label 'Post Title' %><br>
  <%= f.text_field :title %><br>

  <%= f.label 'Post Description' %><br>
  <%= f.text_area :description %><br>

  <%= f.submit "Submit Post" %>
<% end %>

But this correction causes one of the tests to fail, so if you follow the directions in the readme you still won't get to a working form that redirects to the posts index.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
