### ISSUE TITLE
using form_for does not pass the test

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/rails-edit-update-action-readme#16]
I had to reach out to AAQ to pass the code along due to the edit form with form helper form_for did not pass the test, had to use form_tag to pass the test

**Comment by brunogarciagonzalez** [comment]
The test will pass if we make the posts/edit.html.erb:
```
<%= form_for @post do |f| %>
  <%= f.label "Post Title" %><br>
  <%= text_field_tag :title %><br>

  <%= f.label "Post Description" %><br>
  <%= text_area_tag :description %><br>

  <%= submit_tag "Submit Post" %>
<% end %>
```

The needed deviation from the readme being that we need to employ text_field **_tag** and _text_area **_tag**, instead of _text_field_ and _text_area_

**Comment by ghost** [comment]
so the code along will have these tags added to the readme?

**Comment by brunogarciagonzalez** [comment]
I am not sure if it is the best solution, the drawback here being that we are not using the FormBuilder object passed into the block by form_for, and an objective from the lab is to move the student  from form_tag towards form_for.

I found the following StackOverflow post that helps, in that it provides the beginnings of another solution. This solution trying to fix the test itself:
https://stackoverflow.com/questions/17976959/why-is-capybara-not-finding-a-form-element

And when editing the test with the information from that link, it proceeds to produce a runtime error:
```
Failures:

  1) form shows a new form that submits content and redirects and prints out params
     Failure/Error: raise params.inspect
     
     RuntimeError:
       {"utf8"=>"✓", "_method"=>"patch", "post"=>{"title"=>"My edit", "description"=>"My post description"}, "commit"=>"Submit Post", "controller"=>"posts", "action"=>"update", "id"=>"1"}
```

**Comment by rcrdlbl** [comment]
If you look at the [issue I just opened](https://github.com/learn-co-curriculum/rails-edit-update-action-readme/issues/23) you can see what I did to the controller action to make it work

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
