### ISSUE TITLE
solution doesn't pass tests

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/rails-edit-update-action-readme#28]
This form provided in the solution does not pass the tests

<%= form_for @post do |f| %>
  <%= f.label 'Post Title' %><br>
  <%= f.text_field :title %><br>

  <%= f.label 'Post Description' %><br>
  <%= f.text_area :description %><br>

  <%= f.submit "Submit Post" %>
<% end %>

**Comment by maxwellbenton** [comment]
Hi @atxrenegade,

Thank you for spotting this and providing feedback. We've updated this lesson's content and solution, including this form, confirmed that the updated content will pass the tests and believe this issue has been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
