### ISSUE TITLE
Seed data required to follow along with this lesson

### ISSUE THREAD

**Issue by kjoewill** [learn-co-curriculum/rails-edit-update-action-readme#29]
A student cannot follow along because there is no data in the database.  In this lessen there is the following instruction:

> If you open up the browser, navigate to an edit page (such as localhost:3000/articles/2/edit), change some elements in the form, and submit it, it should take you to an error page that prints out the params from the form, such as in the below image:

However, rather than getting to the error described in the lesson, the browser reports the following problem because there are no records to edit in the database:

> ActiveRecord::RecordNotFound in ArticlesController#edit

I think seed data should be provided in seeds.db and the instructions should be chenged to have the student run migrations and then the seeds file.

Thanks!

--Kevin

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
