### ISSUE TITLE
routes don't follow rails convention

### ISSUE THREAD

**Issue by c1505** [learn-co-curriculum/rails-edit-update-action-readme#3]
put 'post/:id', to: 'posts#update' should be put 'posts/:id', to: 'posts#update' .

Throughout the document and specs singular post is used rather than posts relating to the update and edit routes.

**Comment by AnnJohn** [comment]
thanks @c1505 for raising this. we'll be doing an update on our rails curriculum shortly and will address this soon.

**Comment by jmburges** [comment]
:+1:
