### ISSUE TITLE
Missing .rspec file

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/rails-edit-update-action-readme#7]

**Comment by AnnJohn** [comment]
hi @mikeappell i don't think this lesson should have an rspec file. please let me know if you think otherwise; thanks

**Comment by mikeappell** [comment]
Hey @AnnJohn ,

It's more of a codealong than a readme: the learn lesson still expects you to fork, run and pass the tests, so having the .rspec file certainly can't hurt.
