### ISSUE TITLE
Need to follow the "side note" instructions in order to pass spec

### ISSUE THREAD

**Issue by miclp** [learn-co-curriculum/rails-edit-update-action-readme#8]
Line #39 in post_spec.rb only works if you add :edit, and :update to the resources call in the routes file.

The lesson says "on a side note, you could .... " but this was actually necessary to pass the spec as it's written.

**Comment by gj** [comment]
Adding `:edit` and `:update` to the `resources` array is not necessary to pass the spec. The named route for the `update` action functions fine as is. The named route for the `edit` action requires the addition of an `as:` parameter, like so:

``` ruby
get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
```

Fixed here: https://github.com/learn-co-curriculum/rails-edit-update-action-readme/pull/9
